name: Deliveryman
version: ${project.version}
main: cc.ikew.deliveryman.Deliveryman
api-version: 1.17
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  deliveryman:
    aliases:
      - dm
    description: 'opens the deliveryman gui'
    usage: '/deliveryman <menu>'
permissions:
  deliveryman.reload:
    default: false
    description: Lets you reload the config files!